---
# handlers file for openplc
- name: Stop openplc
  become: true
  service:
    name: openplc
    state: stopped
  listen: restart openplc

- name: Sleep between stop and start
  pause:
    seconds: "{{ openplc_restart_sleep_seconds }}"
  listen: restart openplc

- name: Start openplc
  become: true
  service:
    name: openplc
    state: started
  listen: restart openplc
